### ISSUE TITLE
Feedback on version v1.0.0-rc2

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/riscv-acpi-rimt#10]
1. The document mixes the use the terms "RIMT device structures", "RIMT device", and "RIMT device binding" in various places. It is recommended that a single consistent phrase be used throughout the document. "RIMT devices" seems to imply these are specifying some form of device objects and that may be confusing. Using "RIMT structures" or "RIMT nodes" ("nodes" terminology seems quite prevalent in  the ACPI specifications). Likewise "structures" and "entries" seems to be used to  refer to same thing in different parts of the document. It is recommended that  the terminology be cleaned up and used consistently.

2. Document uses PCI sometimes and PCIe sometimes. Consistent use of PCIe is recommended.

3. Is "Platform Device" terminology well known in ACPI? If not a short explanation of should be included to define it.

4. Table 4: Should the field name be Interrupt Number and not Interrupt Wire Number Number to match the description which states its an interrupt number and not the number of a wire? Please add some description about how the connectivity of these wires to an interrupt controller can be discovered. If this is addressed elsewhere then a cross reference suffices.

5. For the revision field, please remove the "1-" from the description in the few places it appears. 

6. ID/Unique ID - please add some clarification about whether these are unique IDs in this table or globally unique IDs and guidelines on how they are to be assigned.

7. For ID mapping arrays please specify what the dimension N denotes. 

8. Provide a paragraph explaining how ID mapping works and why its needed. For platform devices, what is the source ID? For PCIe devices is this the routing ID - bus/device/function number?

9. Platform device binding. 
a. The text states these may be non-PCIe devices. What other form of devices can be represented in this table? 
b. "Unique ID of this device" is confusing as it may be construed as referring to one of the platform devices. Is this intended to be a unique ID of the structure?
c. Please explain "Name" field and what it correlates to. 
d. Reword "Padding is to 32-bit word-aligned". Is there a recommended padding value?

@vlsunil

**Comment by vlsunil** [comment]
@ved-rivos - Again thank you very much for the feedback!. I have addressed the comments as part of https://github.com/riscv-non-isa/riscv-acpi-rimt/pull/12. I will send an updated version soon to ARC over email for review. 

Just one clarification for your comment...

>> Is "Platform Device" terminology well known in ACPI? If not a short explanation of should be included to define it.

Platform device is used in ACPI spec. So, I think we don't need to add more explanation. Please refer https://uefi.org/specs/ACPI/6.5/06_Device_Configuration.html.
