### ISSUE TITLE
use of the terrm signature

### ISSUE THREAD

**Issue by andrewdellow** [riscv-non-isa/riscv-acpi-rimt#11]
the RIMT header has a field called 'signature'.  we should avoid using this terminology unless it is a digital signature over the table contents.

**Comment by vlsunil** [comment]
@andrewdellow : This field is a standard name required for all ACPI tables. REF: https://uefi.org/specs/ACPI/6.5/05_ACPI_Software_Programming_Model.html#system-description-table-header

**Comment by andrewdellow** [comment]
OK.
